version: '3.9'
services:
  postgres:
    container_name: synergylabs_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: synergylabs
    ports:
      - "5432:5432"
    volumes:
      - ./prod:/var/lib/postgresql